<a href="https://colab.research.google.com/github/Celso0408/Graphite-Workflow/blob/main/Graphite_Workflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import getpass
username = getpass.getpass(prompt='GitHub username: ')
password = getpass.getpass(prompt='GitHub password/Token: ')

!git clone https://{username}:{password}@github.com/KIT-Workflows/Graphite-Workflow

GitHub username: ··········
GitHub password/Token: ··········
Cloning into 'Graphite-Workflow'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 21 (delta 7), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (21/21), done.


In [3]:
%cd /content/Graphite-Workflow
!git pull

/content/Graphite-Workflow
Already up to date.


In [27]:
import os, yaml
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

def filter_dicts(common_string, db_dict):
  result = []
  for key, value in db_dict.items():
      if common_string in key:
          result.append(key)
  return result

if __name__ == '__main__':

  with open('db-Workflow.yml') as file:
    db_file_encut = yaml.full_load(file)

  #print(db_file_encut["2023-01-04-16h34m57s-DFT-VASP_vasp_results.yml"])

  # Experimental lattice parameters for Graphite in AB staking
  a_0 = 2.462
  c_0 = 6.707

  common_string = 'DFT-VASP'
  prop_1 = 'ENCUT'
  encut = []
  kpoints = []
  prop_2 = 'total_energy'
  tot_energy = []
  a_lat = []  #'cell_lengths_and_angles'[0]
  c_lat = []  #'cell_lengths_and_angles'[5]


  results_dict_name = filter_dicts(common_string, db_file_encut)

  data_array = np.empty((0, 0))

  for dic_name in results_dict_name:
      tot_energy.append(db_file_encut[dic_name][prop_2])
      encut.append(float(db_file_encut[dic_name]["TABS"]["INCAR"]["ENCUT"]))
      kpoints.append(float(db_file_encut[dic_name]["TABS"]["KPOINTS"]["Rk_length"]))
      a_lat.append(db_file_encut[dic_name]['cell_lengths_and_angles'][0])
      c_lat.append(db_file_encut[dic_name]['cell_lengths_and_angles'][2])

  data_array = np.append(data_array, encut)
  data_array = np.column_stack((data_array, tot_energy))
  data_array = np.column_stack((data_array, kpoints))
  data_array = np.column_stack((data_array, a_lat))
  data_array = np.column_stack((data_array, c_lat))

  # count the number of times that a given value appear in the first column of the array
  dim_array = data_array.shape
  
  # ENCUT
  count_encut = np.sum(data_array[:, 2] == data_array[0, 2])
  data_array = data_array[data_array[:,2].argsort()]
  
  # encut array
  encut_energies = np.empty((0, 0))
  encut_energies = np.append(encut_energies, data_array[dim_array[0]-count_encut:dim_array[0], 0])
  encut_energies = np.column_stack((encut_energies, data_array[dim_array[0]-count_encut:dim_array[0], 1]))
  encut_energies = encut_energies[encut_energies[:,0].argsort()]
  


  # KPOINTS
  count_kpt = np.sum(data_array[:, 0] == data_array[0, 0])
  data_array = data_array[data_array[:,0].argsort()]
  
  # kpoints array
  k_energies = np.empty((0, 0))
  k_energies = np.append(k_energies, data_array[dim_array[0]-count_kpt:dim_array[0], 0])
  k_energies = np.column_stack((k_energies, data_array[dim_array[0]-count_kpt:dim_array[0], 1]))
  k_energies = np.column_stack((k_energies, data_array[dim_array[0]-count_kpt:dim_array[0], 2]))
  k_energies = np.column_stack((k_energies, data_array[dim_array[0]-count_kpt:dim_array[0], 3]))
  k_energies = np.column_stack((k_energies, data_array[dim_array[0]-count_kpt:dim_array[0], 4]))
  k_energies = k_energies[k_energies[:,2].argsort()]
  
  print(data_array)
  print('=========================================')
  print(k_energies)
  

  # # create a figure with a large size
  # fig, ax = plt.subplots(2,1,figsize=(15, 10))


  # ax[0].plot(encut_energies[:,0], encut_energies[:,1],'-ro')
  # ax[0].set_xlabel('ENCUT',Fontsize=20)
  # ax[0].set_ylabel('Tot Energy (eV)', Fontsize=20)
  # ax[0].tick_params(labelsize=18)

  # ax[1].plot(k_energies[:,0], k_energies[:,1],'-ro')
  # ax[1].set_xlabel('KPOINTS',Fontsize=20)
  # ax[1].set_ylabel('Tot Energy (eV)', Fontsize=20)
  # ax[1].tick_params(labelsize=18)
  # plt.show()





[[ 400.          -34.83677791   20.            2.39929496    5.83656628]
 [ 400.          -34.85052871   30.            2.39935454    5.83843305]
 [ 400.          -34.84971641   35.            2.39933033    5.84058701]
 [ 400.          -34.85664338   25.            2.3994461     5.83950229]
 [ 400.          -34.84905682   45.            2.39934965    5.83967123]
 [ 400.          -34.84486334   40.            2.39923123    5.84095242]
 [ 400.          -34.84729205   15.            2.40014755    5.83776523]
 [ 466.66666667  -36.13290935   25.            2.43436356    6.31972109]
 [ 466.66666667  -36.13231172   35.            2.43436828    6.3241326 ]
 [ 466.66666667  -36.12997104   40.            2.43429652    6.32486515]
 [ 466.66666667  -36.13209602   30.            2.43434491    6.32336003]
 [ 466.66666667  -36.13245619   45.            2.43438491    6.32498988]
 [ 466.66666667  -36.12734165   20.            2.43453875    6.31919349]
 [ 466.66666667  -36.10943487   15.            2.43